version: '3'

services:
  app:
    build:
      context: "${DOCKER_FILES_DIR}${PHP_FPM_DOCKER_FILES_DIR}"
      dockerfile: '.dockerfile'
    working_dir: "${NGINX_HTML_FOLDER}"
    volumes:
      - "./app_source:${NGINX_HTML_FOLDER}"
      - "./.log/supervisord/php_fpm:${PHP_FPM_SUPERVISORD_LOGS_FOLDER}"
    depends_on:
      - database

  composer:
     image: composer
     restart: 'no'
     volumes:
      - "./app_source:${COMPOSER_FOLDER}"
     command: install

  httpd:
    build:
      context: "${DOCKER_FILES_DIR}${NGINX_DOCKER_FILES_DIR}"
      dockerfile: '.dockerfile'
    working_dir: "${NGINX_HTML_FOLDER}"
    volumes:
      - "./app_source:${NGINX_HTML_FOLDER}"
      - "./.log/supervisord/nginx:${NGINX_SUPERVISORD_LOGS_FOLDER}"
    ports:
      - "${DOCKER_NGINX_HOST_PORT}:${NGINX_PORT}"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    restart: 'always'
    depends_on:
      - app

  database:
    image: mariadb
    restart: 'always'
    volumes:
      - ./.storage/tmp/db:/var/lib/mysql:cached
    ports:
      - "${DOCKER_MYSQL_HOST_PORT}:${MYSQL_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  app_source:
